'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { ChevronRight, LoaderCircle, Plus, Search, X } from 'lucide-react';
import { EmptyState, ErrorState, PageHeader } from '@/components/ui';
import { api, listResult } from '@/lib/api';
import { formatNumber, formatRupiah } from '@/lib/format';
import type { Customer } from '@/lib/types';

type CustomerListResponse = Customer[] | { data?: Customer[]; items?: Customer[]; total?: number };

export default function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [total, setTotal] = useState(0);
  const [query, setQuery] = useState(''); const [submittedQuery, setSubmittedQuery] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showForm, setShowForm] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await api<CustomerListResponse>(`/customers${submittedQuery ? `?search=${encodeURIComponent(submittedQuery)}` : ''}`); const result = listResult(response); setCustomers(result.data); setTotal(result.total); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Pelanggan tidak dapat dimuat.'); } finally { setLoading(false); } }, [submittedQuery]);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(null); try { await api('/customers', { method: 'POST', body: { name: String(form.get('name') ?? '').trim(), phone: String(form.get('phone') ?? '').trim(), email: String(form.get('email') ?? '').trim() || undefined, address: String(form.get('address') ?? '').trim() || undefined, notes: String(form.get('notes') ?? '').trim() || undefined } }); setShowForm(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Pelanggan tidak dapat disimpan.'); } }
  return <div className="page-enter"><PageHeader eyebrow="Relasi" title="Pelanggan" description={loading ? 'Memuat pelanggan...' : `${formatNumber(total)} pelanggan terdaftar`} action={<button className="btn-primary" onClick={() => setShowForm(true)}><Plus className="size-5" aria-hidden="true" />Pelanggan baru</button>} />
    <form className="relative mb-5" role="search" onSubmit={(event) => { event.preventDefault(); setSubmittedQuery(query.trim()); }}><Search className="absolute left-4 top-3.5 size-5 text-muted" aria-hidden="true" /><label className="sr-only" htmlFor="customer-query">Cari nama atau nomor HP</label><input className="field pl-12 pr-24" id="customer-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nama atau nomor HP" /><button className="absolute right-1.5 top-1.5 min-h-9 rounded-lg bg-moss px-3 text-sm font-semibold text-white">Cari</button></form>
    {error ? <ErrorState message={error} retry={() => void load()} /> : loading ? <div className="grid gap-3 md:grid-cols-2">{Array.from({ length: 6 }, (_, index) => <div className="skeleton h-28" key={index} />)}</div> : customers.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{customers.map((customer) => <Link className="card group flex min-h-28 items-center gap-4 transition-colors hover:border-moss/40" href={`/customers/${customer.id}`} key={customer.id}><span className="grid size-11 shrink-0 place-items-center rounded-full bg-wash font-semibold text-moss">{customer.name.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><strong className="block truncate">{customer.name}</strong><span className="block text-sm text-muted">{customer.phone}</span><span className="mt-1 block text-xs text-muted">{formatNumber(customer.totalOrders ?? 0)} order · {formatRupiah(customer.totalSpending ?? 0)}</span></span><ChevronRight className="size-5 text-muted" aria-hidden="true" /></Link>)}</div> : <EmptyState title="Pelanggan tidak ditemukan" description={submittedQuery ? 'Coba nama atau nomor HP lain.' : 'Tambahkan pelanggan saat menerima order pertama.'} />}
    {showForm ? <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 p-0 sm:place-items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="new-customer-title"><form className="w-full max-w-lg rounded-t-3xl bg-white p-5 shadow-xl sm:rounded-2xl" onSubmit={create}><div className="flex items-center justify-between"><div><p className="eyebrow">Pelanggan</p><h2 className="section-title" id="new-customer-title">Data baru</h2></div><button className="icon-button" type="button" onClick={() => setShowForm(false)} aria-label="Tutup"><X className="size-5" aria-hidden="true" /></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className="field-label" htmlFor="customer-name">Nama *</label><input className="field" id="customer-name" name="name" required autoFocus /></div><div><label className="field-label" htmlFor="customer-phone">Nomor HP *</label><input className="field" id="customer-phone" name="phone" type="tel" required /></div><div><label className="field-label" htmlFor="customer-email">Email</label><input className="field" id="customer-email" name="email" type="email" /></div><div><label className="field-label" htmlFor="customer-address">Alamat</label><input className="field" id="customer-address" name="address" /></div><div className="sm:col-span-2"><label className="field-label" htmlFor="customer-notes">Catatan</label><textarea className="field min-h-20" id="customer-notes" name="notes" /></div></div><button className="btn-primary mt-5 w-full"><LoaderCircle className="hidden size-4" aria-hidden="true" />Simpan pelanggan</button></form></div> : null}
  </div>;
}
